---
- hosts: jenkinsmaster
  roles:
    - role: wunzeco.java
      java_package: openjdk-8-jdk
    - role: wunzeco.jenkins 
      jenkins_version: 2.89.4
    - role: jdauphant.ssl-certs
      ssl_certs_local_privkey_path: 'files/ssl/multicast-media.com.key'
      ssl_certs_local_cert_path: 'files/ssl/multicast-media.com.crt'
      ssl_certs_common_name: 'multicast-media.com'
      ssl_certs_path_owner: 'root'
      ssl_certs_path_group: 'root'
      ssl_certs_path: '/etc/ssl/multicast-media.com'
      ssl_certs_privkey_path: '/etc/ssl/web/multicast-media.com.key'
      ssl_certs_cert_path: '/etc/ssl/web/multicast-media.com.crt'
    - role: jdauphant.nginx
      nginx_sites:
        custom_bar:
          template: multicast-media.com.conf.j2
          server_name: multicast-media.com
  tasks:
    - name: change listen host address for jenkins
      lineinfile:
        path: /etc/default/jenkins
        regexp: '^(.*)JENKINS_ARGS=(.*)'
        line: 'JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --httpListenAddress=127.0.0.1"'
        backrefs: yes
    - name: Restart Jenkins
      service: name=jenkins state=restarted

- hosts: jenkinslave
  roles: 
    - role: wunzeco.java
      java_package: openjdk-8-jdk
    - role: wunzeco.jenkins
      jenkins_version: 2.89.4
   
